/* 三季圖庫資料：一張圖片一筆。episode 是官方累計話數；立繪為 null。
 * 標題與短句為本館觀賞筆記；source 是這張圖的官方來源頁。
 */
"use strict";
window.AkaneGalleryItems = [
  {
    id: "s1-ep06-5",
    title: "泰迪熊與她的日常",
    type: "still",
    season: 1,
    episode: 6,
    order: 5,
    description: "帶著泰迪熊的茜，鏡頭留下她驚訝的神情。",
    source: "https://ichigoproduction.com/Season1/story/06.html",
    width: 1100,
    height: 619,
  },
  {
    id: "s1-ep06-6",
    title: "安靜下來的房間",
    type: "still",
    season: 1,
    episode: 6,
    order: 6,
    description: "偏冷的室內光影，映出她沉默的側臉。",
    source: "https://ichigoproduction.com/Season1/story/06.html",
    width: 1100,
    height: 619,
  },
  {
    id: "s1-ep07-1",
    title: "把脆弱留在鏡頭裡",
    type: "still",
    season: 1,
    episode: 7,
    order: 1,
    description: "近景中的淚水，記錄她面對困境時的情緒。",
    source: "https://ichigoproduction.com/Season1/story/07.html",
    width: 1100,
    height: 619,
  },
  {
    id: "s1-ep07-5",
    title: "螢幕後的一雙眼睛",
    type: "still",
    season: 1,
    episode: 7,
    order: 5,
    description: "手機遮住半張臉，眼神仍然藏不住情緒。",
    source: "https://ichigoproduction.com/Season1/story/07.html",
    width: 1100,
    height: 619,
  },
  {
    id: "starlight",
    title: "眼中亮起的星光",
    type: "still",
    season: 1,
    episode: 8,
    order: 1,
    description: "明亮的星形眼眸，留下她進入表演狀態的一瞬。",
    source: "https://ichigoproduction.com/Season1/story/08.html",
    width: 1100,
    height: 619,
  },
  {
    id: "insight",
    title: "靠近角色的心",
    type: "still",
    season: 1,
    episode: 8,
    order: 2,
    description: "同一話的另一個鏡頭，欣賞茜不同的表情與演出。",
    source: "https://ichigoproduction.com/Season1/story/08.html",
    width: 1100,
    height: 619,
  },
  {
    id: "s1-ep08-3",
    title: "有人一起向前",
    type: "still",
    season: 1,
    episode: 8,
    order: 3,
    description: "茜與節目共演者同框，留下相互支持的畫面。",
    source: "https://ichigoproduction.com/Season1/story/08.html",
    width: 1100,
    height: 619,
  },
  {
    id: "s2-ep12-5",
    title: "排練室的側影",
    type: "still",
    season: 2,
    episode: 12,
    order: 5,
    description: "走進第二季，從排練中的側臉重新認識演員茜。",
    source: "https://ichigoproduction.com/Season2/story/12.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s2-ep13-4",
    title: "藏不住的微笑",
    type: "still",
    season: 2,
    episode: 13,
    order: 4,
    description: "柔和的近景，捕捉嘴角與眼神間細微的變化。",
    source: "https://ichigoproduction.com/Season2/story/13.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s2-ep15-5",
    title: "劇本在手，角色在心",
    type: "still",
    season: 2,
    episode: 15,
    order: 5,
    description: "排練中的茜與佳奈同框，手裡的劇本也是演員日常的一部分。",
    source: "https://ichigoproduction.com/Season2/story/15.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s2-ep18-2",
    title: "憧憬住在眼裡",
    type: "still",
    season: 2,
    episode: 18,
    order: 2,
    description: "年幼的茜眼中亮起光，這段回憶按實際播出話數收錄。",
    source: "https://ichigoproduction.com/Season2/story/18.html",
    width: 1200,
    height: 675,
  },
  {
    id: "childhood",
    title: "小小的她，大大的憧憬",
    type: "still",
    season: 2,
    episode: 18,
    order: 3,
    description: "第十八話回顧她走向演員之路的起點。",
    source: "https://ichigoproduction.com/Season2/story/18.html",
    width: 1200,
    height: 675,
  },
  {
    id: "performance",
    title: "舞台把目光留下",
    type: "still",
    season: 2,
    episode: 18,
    order: 5,
    description: "鞘姬造型的近景，讓表情與舞台光影成為主角。",
    source: "https://ichigoproduction.com/Season2/story/18.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s2-ep19-4",
    title: "鞘姬的目光",
    type: "still",
    season: 2,
    episode: 19,
    order: 4,
    description: "白髮與舞台衣裝，展現日常之外的另一種氣質。",
    source: "https://ichigoproduction.com/Season2/story/19.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s2-ep20-3",
    title: "在紅色舞台上",
    type: "still",
    season: 2,
    episode: 20,
    order: 3,
    description: "強烈的舞台色彩與流動髮絲，留下戲劇性的演出畫面。",
    source: "https://ichigoproduction.com/Season2/story/20.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s2-ep20-6",
    title: "演出裡的一點光",
    type: "still",
    season: 2,
    episode: 20,
    order: 6,
    description: "鞘姬的眼眸近景，讓情緒在光影之間浮現。",
    source: "https://ichigoproduction.com/Season2/story/20.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s2-ep21-6",
    title: "潛入藍色的瞬間",
    type: "still",
    season: 2,
    episode: 21,
    order: 6,
    description: "水色映在茜的髮絲與臉上，收藏這一幕清透的藍。",
    source: "https://ichigoproduction.com/Season2/story/21.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s2-ep22-4",
    title: "風裡的溫柔",
    type: "still",
    season: 2,
    episode: 22,
    order: 4,
    description: "夕光與長髮交織，留下回望時的柔和神情。",
    source: "https://ichigoproduction.com/Season2/story/22.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s2-ep22-6",
    title: "讓心情說出來",
    type: "still",
    season: 2,
    episode: 22,
    order: 6,
    description: "暖色鏡頭中的表情變化，也是一段值得留下的瞬間。",
    source: "https://ichigoproduction.com/Season2/story/22.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s2-ep24-2",
    title: "暗處仍然有光",
    type: "still",
    season: 2,
    episode: 24,
    order: 2,
    description: "暗色背景讓她的藍綠眼眸與微小表情更加清晰。",
    source: "https://ichigoproduction.com/Season2/story/24.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s3-ep25-5",
    title: "休息也是生活的一部分",
    type: "still",
    season: 3,
    episode: 25,
    order: 5,
    description: "第三季開場的日常畫面：倚著手臂、把步調放慢的茜。",
    source: "https://ichigoproduction.com/Season3/story/25.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s3-ep26-5",
    title: "認真到有點可愛",
    type: "still",
    season: 3,
    episode: 26,
    order: 5,
    description: "近景留下略帶誇張的反應，收藏她生活中的另一種表情。",
    source: "https://ichigoproduction.com/Season3/story/26.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s3-ep29-1",
    title: "夜色裡的藍",
    type: "still",
    season: 3,
    episode: 29,
    order: 1,
    description: "側臉與髮尾的漸層，在夜晚的光影中格外鮮明。",
    source: "https://ichigoproduction.com/Season3/story/29.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s3-ep31-6",
    title: "花束與微笑",
    type: "still",
    season: 3,
    episode: 31,
    order: 6,
    description: "一束花與一個微笑，讓鏡頭停留在柔和的瞬間。",
    source: "https://ichigoproduction.com/Season3/story/31.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s3-ep33-6",
    title: "凝視的溫度",
    type: "still",
    season: 3,
    episode: 33,
    order: 6,
    description: "帽簷下的雙眼特寫，留下細膩而安靜的表情。",
    source: "https://ichigoproduction.com/Season3/story/33.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s3-ep34-4",
    title: "再一次，星光亮起",
    type: "still",
    season: 3,
    episode: 34,
    order: 4,
    description: "長髮與星形眼眸同框，記錄第三季中的表演瞬間。",
    source: "https://ichigoproduction.com/Season3/story/34.html",
    width: 1200,
    height: 675,
  },
  {
    id: "s3-ep34-5",
    title: "夜裡沒說完的話",
    type: "still",
    season: 3,
    episode: 34,
    order: 5,
    description: "帽簷與深藍光影下，眼神成為這張劇照的中心。",
    source: "https://ichigoproduction.com/Season3/story/34.html",
    width: 1200,
    height: 675,
  },
  {
    id: "casual",
    title: "風吹過的日常",
    type: "visual",
    season: 2,
    episode: null,
    order: 0,
    description: "第二季官方私服立繪：米白長裙、棕色外套與流動的髮絲。",
    source: "https://ichigoproduction.com/Season2/chara/akane.html",
    width: 720,
    height: 940,
  },
  {
    id: "stage",
    title: "走進鞘姬的世界",
    type: "visual",
    season: 2,
    episode: null,
    order: 1,
    description: "第二季官方舞台衣裝：茜在《東京 Blade》中飾演鞘姬的造型。",
    source: "https://ichigoproduction.com/Season2/chara/akane.html",
    width: 720,
    height: 940,
  },
];
